### ISSUE TITLE
Cannot run on Windows10

### ISSUE THREAD

**Issue by ice1000** [Heptagon196/Maze#1]
![image](https://cloud.githubusercontent.com/assets/16398479/25051217/17b19d70-217e-11e7-9062-8de80e1a9bc5.png)

And perhaps 'make.bat' would be better to be like

```shell
@echo off
cd src
g++ -c Map.cpp --std=c++11
g++ main.cpp Map.o -o ../Maze --std=c++11
cd ..
```

**Comment by EntropyIncreaser** [comment]
macOS also not supported... cuz mac doesn't have `conio.h`.

**Comment by Heptagon196** [comment]
mac使用clang应该可以通过编译，把src下的Makefile的CC改为clang++就可以。反正我在linux上用clang通过了编译，mac买不起。
windows也许是我忘了-lpthread?然而我wine都编译成功了。我有空试一下虚拟机。
昨晚写得十分匆忙，而且我妈不停地叫我快复习半期考试……目前只能优先保证linux上运行正常，在windows下即使成功运行也可能会有绘图效率低的问题，也许只能下周改了。

**Comment by Heptagon196** [comment]
mac使用clang应该可以通过编译，把src下的Makefile的CC改为clang++就可以。我在linux上用clang通过编译，mac买不起。
windows也许是我忘了-lpthread?然而我wine都编译成功了。
昨晚写得十分匆忙，而且我妈不停地叫我快复习半期考试……目前只能优先保证linux上运行正常，在windows下即使成功运行也可能会有绘图效率低的问题，也许只能下周改了。

**Comment by EntropyIncreaser** [comment]
事实上mac没有`conio.h`只有`curses.h`，我在试着加对于mac的支持

**Comment by Heptagon196** [comment]
刚刚试了一下，c++11的thread在Windows下表现似乎不好，已经删去，在XP下正常运行(使用MinGW编译，g++5.1.0)。

**Comment by Heptagon196** [comment]
linux下也没有conio.h，我在linux下没有使用这个头文件。如果你是手动编译可以尝试加上-Dlinux
我对控制台彩色输出的linux实现是使用控制台转义符。

**Comment by ice1000** [comment]
![image](https://cloud.githubusercontent.com/assets/16398479/25061592/9a6e302a-21ec-11e7-9efe-d1f516ac20f6.png)


 WTF，难道是我的GCC版本低了？

**Comment by ice1000** [comment]
我是重新clone了的

**Comment by Heptagon196** [comment]
刚刚下了个windows10在虚拟机里测试，一切正常……
你用的编译器版本？

**Comment by ice1000** [comment]
D:\git-repos\algo4j\jni>gcc -v
Using built-in specs.
COLLECT_GCC=D:\Program Files\Haskell Platform\8.0.2\mingw\bin/realgcc.exe
COLLECT_LTO_WRAPPER=D:/Program\ Files/Haskell\ Platform/8.0.2/mingw/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-5.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --with-gxx-include-dir=/mingw64/include/c++/5.2.0 --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-version-specific-runtime-libs --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=http://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 5.2.0 (Rev3, Built by MSYS2 project)


Haskell Platform 自带的

**Comment by Heptagon196** [comment]
![virtualbox_windows10_16_04_2017_11_19_35](https://cloud.githubusercontent.com/assets/17093400/25068449/c5a1af60-2296-11e7-8e4f-c8e125ccc6f8.png)
？？？
无法重现

**Comment by ice1000** [comment]
我使用DevCpp编译了一下，看到了如下信息：

编译可以通过，但是有Linkage Error，我人脑.unique()了一下，大概是这样的：

C:\Users\ice1000\AppData\Local\Temp\ccsceylJ.o	main.cpp:(.text+0x55e): undefined reference to `color(int, int)'
C:\Users\ice1000\AppData\Local\Temp\ccsceylJ.o	main.cpp:(.text+0x8c6): undefined reference to `gotoxy(int, int)'
C:\Users\ice1000\AppData\Local\Temp\ccsceylJ.o	main.cpp:(.text+0x3114): undefined reference to `unhidecursor()'
C:\Users\ice1000\AppData\Local\Temp\ccsceylJ.o	main.cpp:(.text+0x3173): undefined reference to `hidecursor()'
C:\Users\ice1000\AppData\Local\Temp\ccsceylJ.o	main.cpp:(.text+0x47e5): undefined reference to `clearcolor()'
C:\Users\ice1000\AppData\Local\Temp\ccsceylJ.o	main.cpp:(.text+0x47ea): undefined reference to `clear()'


难道我缺了什么dll？

**Comment by ice1000** [comment]
注意我加了对cpp文件的include的

```cpp
#include "Conio+.h"
#include "Conio+.cpp"
#include "Map.h"
#include "Map.cpp"
```

**Comment by Heptagon196** [comment]
那个纯粹是我瓜了一下……
昨天想把Conio+的申明与定义分离，结果我cp Conio+.h Conio+.cpp后忘了把开头的#ifndef CONIOPLUS_H给删了……
总之和这个问题没有关系，我已经删掉了。

**Comment by ice1000** [comment]
好了，现在当我把main.cpp的最顶部改成

```cpp
```

后，程序正常运行。但是make.bat还是不行。。。
建个议，把make.bat改一下。。弄个ifdef什么的。。

```batch
REM make.bat
echo #define WIN >> win.h
```

然后在main.cpp里面

```cpp
#include "win.h"
#ifdef WIN
#include "两个cpp"
#endif
```

就好

**Comment by ice1000** [comment]
真奇妙，这是个诡异的问题。
我把GCC换成了DevCpp的就没问题了。
可能我安装了假的Haskell Platform
